name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Set up GitVersion
      run: gitversion /updateassemblyinfo

    - name: Build
      run: dotnet build --configuration Release /p:Version=$(gitversion /showvariable SemVer)

    - name: Test
      run: dotnet test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-web-app-name'
        package: './publish/**/*.zip'
        slot-name: 'production' # You can specify the deployment slot
