name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.100'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dotnet-gitversion
      run: dotnet tool install -g GitVersion.Tool

    - name: Get current version
      id: get_version
      run: echo "::set-output name=version::$(grep -oP '(?<=AssemblyVersion\(")[^"]*' WebApplication1/Properties/AssemblyInfo.cs)"

    - name: Increment version
      id: increment_version
      run: echo "::set-output name=version::$(echo ${{ steps.get_version.outputs.version }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')"
  
    - name: Set version in all AssemblyInfo.cs files
      uses: secondbounce/assemblyinfo-update@v2
      with:
        version: steps.increment_version.outputs.version
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lab4mwo'    
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

    - name: Install GitVersion (for updating assembly info)
      run: |
        wget -q -O gitversion.zip https://github.com/GitTools/GitVersion/releases/download/5.7.0/GitVersion_5.7.0.zip
        unzip -l gitversion.zip
        unzip -q gitversion.zip -d gitversion
        export PATH=$PATH:$(pwd)/gitversion
      shell: bash

    - name: Update AssemblyInfo with GitVersion
      run: gitversion /updateassemblyinfo
      shell: bash
