name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Install GitVersion
      run: |
        wget -q -O gitversion.zip https://github.com/GitTools/GitVersion/releases/download/5.7.0/GitVersion_5.7.0.zip
        unzip -l gitversion.zip
        unzip -q gitversion.zip -d gitversion
        export PATH=$PATH:$(pwd)/gitversion
      shell: bash

    - name: Show current directory
      run: pwd

    - name: List files in the current directory
      run: ls -al

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-web-app-name'
        package: './publish/**/*.zip'
        slot-name: 'production' # You can specify the deployment slot
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

    - name: Install GitVersion (for updating assembly info)
      run: |
        wget -q -O gitversion.zip https://github.com/GitTools/GitVersion/releases/download/5.7.0/GitVersion_5.7.0.zip
        unzip -l gitversion.zip
        unzip -q gitversion.zip -d gitversion
        export PATH=$PATH:$(pwd)/gitversion
      shell: bash

    - name: Update AssemblyInfo with GitVersion
      run: gitversion /updateassemblyinfo
      shell: bash
